# Generated by Django 5.2.4 on 2025-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nascimento', models.DateField()),
            ],
        ),
    ]
